React Capstone
a-laarabi/React-Capstone pull request #5
Opened 2022-09-09 17:55 UTC by a-laarabi

# What ? 
> In this pull request, I created a web application that displays the most famous games and their details below a screenshot for the Homepage 👍

![Capture d’écran 2022-09-09 à 17 16 02](https://user-images.githubusercontent.com/61356975/189406427-b094e8fa-261a-470a-a238-84a5d103c2b4.png)

## highlights
- Use React documentation.
- Use React components.
- Use React props.
- Use React Router.
- Connect React and Redux.
- Handle events in a React app.
- Write integration tests with a React testing library.
- Use styles in a React app.
- Use React life cycle methods.
- Apply React best practices and language style guides in code.
- Use store, actions and reducers in React.
- I follow these [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs))

### here is a screen for the test file :

<img width="449" alt="Capture d’écran 2022-09-09 à 18 54 08" src="https://user-images.githubusercontent.com/61356975/189414185-08c0e27f-5a70-4cfc-8195-ed6407f6193a.png">

# Cheer and happy reviewing 🥇

2022-09-09 19:00 UTC, vickymarz requested changes
Hi @a-laarabi, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- All tests are passing ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Good UI design ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-09 19:00 UTC, victorokoroji commented on src/components/Games/Home.js
> +    </>
- [ ] I must really commend your design. It looks good 👍🏽 . I really think you should work on the desktop view as well because this is a web app and as such should be responsive and adaptable to both desktop and mobile views. 

I want you to know that most of your app users will use the desktop version so make it good 😄. Please make your data fill the whole page, and not just a part of the page 👍🏽  

![image](https://user-images.githubusercontent.com/63473584/189417417-16325831-862e-4f4c-854b-c5a3894ba99d.png)

2022-09-09 19:00 UTC, victorokoroji commented on src/App.js
> +                <Home />
[OPTIONAL]

- I think will be better if your `<HomeHeader />` component is added inside the `<Home />` so that you will have a single component in the route which is a lot cleaner. Kindly consider that 👍🏽

2022-09-09 19:00 UTC, victorokoroji commented on src/redux/actions.js
> +const API_KEY = '6b2632491420425bb6bc1bfb81341be8';
[OPTIONAL]

- I would strongly recommend you always store all your sensitive or secret information such as your API_KEY in an environment variable so that it does not show in the repo which helps to prevent any malicious activity on your website. Please add your API_KEY to an environment variable 👍🏽

2022-09-09 19:00 UTC, victorokoroji commented on src/redux/actions.js
> +  async () => {
[OPTIONAL]

- I would strongly recommend that when using async/await, you should always wrap it in a try/catch so as to give you more flexibly in terns of error handling in case there are errors 👍🏽

2022-09-09 19:00 UTC, victorokoroji commented on src/redux/actions.js
> +// export default setGames;
- [ ] Kindly remove this unused comment to make your code look clean 👍🏽

2022-09-09 19:00 UTC, victorokoroji commented on src/components/HomeHeader.js
> +    <div className="homeHeader">
- [ ] Kindly use the `<header>` tag to wrap this section instead of a `div` since this represents the introductory content of your application to make your web app semantic 👍🏽

2022-09-09 19:00 UTC, victorokoroji commented on src/components/Header.js
> +export default Header;
[OPTIONAL]

- I think it will be better if you name this component something like `<Navigation />`or `<Nav />` for easier understanding and clarity for anyone indenting to visit or maintain your code 👍🏽

2022-09-09 19:00 UTC, victorokoroji commented on src/components/Games/Home.js
> +  dispatch(setGames());
[OPTIONAL]
 
- I think it will be better if you call your  `dispatch(setGames())` in a `useEFfect` so that it triggers on page load and subsequent re-render which is much better 👍🏽 ,

2022-09-09 19:00 UTC, victorokoroji commented on src/components/HomeHeader.js
> +        <input type="text" placeholder="Search..." />
- [ ] Kindly implement the search functionality and use the Filter stateless component to filter data retrieved from the API based on the search result by the user 👍🏽 .

2022-09-09 19:00 UTC, victorokoroji commented on README.md
> +> To successfully utilize this project first of all you need to clone or download the repository.
- [ ] KIndly highlight the steps it will take to get the project to run locally 👍🏽

2022-09-09 19:00 UTC, victorokoroji commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] The link to your MIT license is currently broken as the MIT file is currently not in your repo. Kindly add the MIT license file 👍🏽

2022-09-09 19:00 UTC, vickymarz commented on src/__test__/home.test.js
> +});
- [ ] I think writing just one test is not sufficient to validate the proper running of your application. Please write more tests. You can write unit tests for several components of the app and some pure functions in Redux code 👍🏽 .

2022-09-10 01:24 UTC, Rustamxon7 approved these changes
## Hello @a-laarabi👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-02 12:59 UTC, merged